### ISSUE TITLE
Pronto::RailsBestPractices gets freezed

### ISSUE THREAD

**Issue by danigonza** [mmozuras/pronto-rails_best_practices#2]
When I run Pronto::RailsBestPractices runner the excution stops

```
Running Pronto::Brakeman
Running Pronto::Coffeelint
Running Pronto::Fasterer
Running Pronto::Flay
Running Pronto::Haml
Running Pronto::JSHint
Running Pronto::RailsBestPractices
/*** Stops HERE! ****/
```

Any reason?

**Comment by mmozuras** [comment]
@danigonza stops without any errors? I've tried to reproduce, but couldn't. Could you create (or point to) a repo, which could be used for reproduction?

**Comment by mmozuras** [comment]
Closing this issue. @danigonza please re-open if you still encounter this issue and provide more information for reproduction 🙇.
