### ISSUE TITLE
"Restrict auto-generated routes" warning being triggered despite route being properly restricted

### ISSUE THREAD

**Issue by dennmart** [mmozuras/pronto-rails_best_practices#3]
I have a strange issue popping up with a Rails 4.2.6 app using Pronto with this runner.

In the app, pronto-rails_best_practices runner is telling us to [restrict auto-generated routes](http://rails-bestpractices.com/posts/2011/08/19/restrict-auto-generated-routes/), but the error message is the following:

```
config/routes.rb:65 W: Restrict auto-generated routes comments (only: [])
```

That specific line in `config/routes.rb` is the following:

``` ruby
resources :comments, only: [:create, :update, :destroy]
```

The `CommentsController` in our app contains those three actions (`create`, `update` and `destroy`) along with a few private methods. Running `rails_best_practices` in the app by itself doesn't trigger any warnings, so it's only happening when Pronto uses this runner.

This route was also updated in the branch where Pronto is running and giving the error - the `update` action was added, which isn't in the `master` branch, so that might be a reason why the strange error message is being triggered.

Any idea what could be causing it? Let me know if you need additional information on this.

**Comment by nbekirov** [comment]
As I'm looking into this and was wondering if you have anything in `rails_best_practices.yml` (specifically related to `RemoveUnusedMethodsInControllersCheck`)?

**Comment by dennmart** [comment]
`RemoveUnusedMethodsInControllersCheck` is currently commented out in [our configuration](https://gist.github.com/dennmart/b6e725b0f6039737f18384d31a6c638b).

**Comment by nbekirov** [comment]
@dennmart Are there any namespace, inheritance or other peculiar details about the comments controller? 💭 

I'm still unable to reproduce this issue in an example app. Can you?

**Comment by dennmart** [comment]
@nbekirov Thanks for looking into this. After seeing your comment, I continued digging around and possibly found out the culprit.

We're using Pronto with multiple runners on our app (specifically: pronto-rubocop, pronto-brakeman, pronto-fasterer, pronto-scss, pronto-scss and pronto-rails_best_practices). I took out all other runners and just kept pronto-rails_best_practices, and the warning didn't appear. Then I started adding the other ones one by one, and when I added pronto-brakeman, the "restrict auto-generated routes" warning came up. When running Pronto with all the runners except pronto-brakeman, the warning does not pop up. So Brakeman / pronto-brakeman is causing some issue here.

I was able to replicate this in our app and in a fresh Rails app. I'm not sure if this is an issue for pronto-rails_best_practices or pronto-brakeman. Let me know if you prefer for me to move this issue to the pronto-brakeman repo.

**Comment by dennmart** [comment]
I just noticed that this issue has already been reported in https://github.com/mmozuras/pronto/issues/80. I'm able to replicate it running the same order of runners. I'll close this issue and follow the existing issue. Thanks for looking into it @nbekirov!
